match/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('match/', include('qaa.urls')),
    path('admin/', admin.site.urls),
]

qaa/urls.py
from django.urls import path
from . import views


app_name = 'qaa'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.create, name='create'),
    path('<int:question_id>/edit/', views.edit, name='edit'),
    path('<int:question_id>/delete/', views.delete, name='delete'),
    path('start/', views.start, name='start'),
    path('<int:question_id>/add_answer/', views.add_answer, name='add_answer'),
    path('clear/', views.clear, name='clear'),
]

qaa/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=50)
    question_answer = models.CharField(max_length=50)
    human_answer = models.CharField(max_length=50, default='', blank=True)

    def check_answers(self):
        if self.question_answer.lower() == self.human_answer.lower():
            return 'Верно'
        else:
            return 'Неверно'

qaa/views.py
from django.shortcuts import render, redirect
from django.views import generic

from .models import Question


class IndexView(generic.ListView):
    model = Question
    template_name = 'qaa/index.html'
    context_object_name = 'list_of_questions'


def create(request):
    Question.objects.create(
        question_text=request.POST['question'],
        question_answer=request.POST['answer']
    )
    return redirect('qaa:index')


def edit(request, question_id):
    question = Question.objects.get(id=question_id)
    if request.method == 'GET':
        return render(request, 'qaa/edit.html', {'question': question})
    else:
        question.question_text = request.POST['question']
        question.question_answer = request.POST['answer']
        question.save()
        return redirect('qaa:index')


def delete(request, question_id):
    Question.objects.get(id=question_id).delete()
    return redirect('qaa:index')


def start(request):
    questions = Question.objects.all()
    questions_with_answer = []
    question_without_answer = None
    count_of_correct_answers = 0

    for q in questions:
        if q.human_answer:
            questions_with_answer.append(q)
        else:
            question_without_answer = q
            break

    for question in questions_with_answer:
        if question.human_answer == question.question_answer:
            count_of_correct_answers += 1

    return render(request, 'qaa/start.html', {
        'questions_with_answer': questions_with_answer,
        'question_without_answer': question_without_answer,
        'count_of_correct_answers': count_of_correct_answers,
        'count_of_answers': f'{len(questions)} ({100 // len(questions) * count_of_correct_answers}%)'
    })


def add_answer(request, question_id):
    question = Question.objects.get(id=question_id)

    if question.question_answer.lower() == request.POST['human_answer'].lower():
        question.human_answer = question.question_answer
    else:
        question.human_answer = request.POST['human_answer']

    question.save()
    return redirect('qaa:start')


def clear(request):
    Question.objects.all().delete()
    return redirect('qaa:index')

qaa/templates/qaa/edit.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'qaa/style.css' %}">
</head>

<body>
    <h2>{{question.question_text}} - {{question.question_answer}}</h2>

    <form method="POST">
        {% csrf_token %}
        Введите новый вопрос:&thinsp;<input type="text" name="question" value="{{ question.question_text }}"><br>
        Введите новый ответ:&ensp;&thinsp;&thinsp;<input type="text" name="answer"
            value="{{ question.question_answer }}"><br>
        <button type="submit">Изменить</button>
    </form>
</body>

</html>

qaa/templates/qaa/index.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'qaa/style.css' %}">
</head>

<body>
    <form action="{% url 'qaa:create' %}" method="POST">
        {% csrf_token %}
        Введите вопрос:&thinsp;<input type="text" name="question" required autofocus><br>
        Введите ответ:&ensp;&thinsp;&thinsp;<input type="text" name="answer" required><br>
        <input type="submit" class="add_q" value="Добавить">
    </form>

    --------------------------------------------------------<br><br>

    {% if list_of_questions %}
    {% for question in list_of_questions %}
    <b>Вопрос:</b> {{ question.question_text }}<br>
    <b>Ответ:</b> {{ question.question_answer }}<br>

    {% if question.human_answer %}
    <b>Ответ человека:</b> {{ question.human_answer }}<br>
    {% endif %}

    <a href="{% url 'qaa:edit' question.id %}">Изменить</a> | <a href="{% url 'qaa:delete' question.id %}"
        class="delete">Удалить</a><br>
    --------------------------<br>
    {% endfor %}
    --------------------------------------------------------<br>
    <a href="{% url 'qaa:start' %}">Начать тест</a>
    <a href="{% url 'qaa:clear' %}" class="delete">Отчистить</a>
    {% else %}
    Вопросов нет
    {% endif %}
</body>

</html>

qaa/templates/qaa/start.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'qaa/style.css' %}">
</head>

<body>
    {% if questions_with_answer %}
    {% for question in questions_with_answer %}
    <b>Вопрос:</b> {{ question.question_text }}<br>
    <b>Ответ:</b> {{ question.question_answer }}<br>
    <b>Ваш ответ:</b> {{ question.human_answer }} <span class="correct">({{question.check_answers}})</span><br><br>
    {% endfor %}
    {% else %}
    <b>Вопрос:</b> {{ question_without_answer.question_text }}
    <form action="{% url 'qaa:add_answer' question_without_answer.id %}" method="POST">
        {% csrf_token %}
        <b>Ваш ответ:</b> <input type="text" name="human_answer" required autofocus>
        <button type="submit">Отправить</button>
    </form>
    {% endif %}

    {% if questions_with_answer and question_without_answer != None %}
    <b>Вопрос:</b> {{ question_without_answer.question_text }}
    <form action="{% url 'qaa:add_answer' question_without_answer.id %}" method="POST">
        {% csrf_token %}
        <b>Ваш ответ:</b> <input type="text" name="human_answer" required autofocus>
        <button type="submit">Отправить</button>
    </form>
    {% endif %}

    {% if questions_with_answer and question_without_answer == None %}
    ----------------------------------------------<br>
    Количество верных ответов: <b>{{ count_of_correct_answers }} из {{ count_of_answers }}</b><br><br>
    <button type="button"><a href="{% url 'qaa:index' %}">На главную</a></button>
    {% endif %}
</body>

</html>